### ISSUE TITLE
Experiencing Errors

### ISSUE THREAD

**Issue by bobthegamedevelopment** [PackeTsar/ASA-Cleanup#4]
Getting the following errors when attempting to run against text file containing "show access-list"

Traceback (most recent call last):
  File "ASA-Cleanup.py", line 633, in <module>
  File "ASA-Cleanup.py", line 113, in acl_hit_analysis
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
[20228] Failed to execute script ASA-Cleanup

**Comment by bobthegamedevelopment** [comment]
May be related to size of the file. 60475 lines. If I break the file into chunks (haven't tested past 300 lines) it works no problem. Trying to run against the entire chunk is failure.
