### ISSUE TITLE
The number 550094154

### ISSUE THREAD

**Issue by camwin** [PackeTsar/ASA-Cleanup#8]
For some reason this script trips up numbers like "550094154" in the hit count. Any idea why?

**Comment by PackeTsar** [comment]
Can you send some example data so I can reproduce it?

**Comment by camwin** [comment]
access-list inside line 122 extended permit udp any any eq ntp (hitcnt=550094154) 0x29fc48ca 

If I change 550094154 to 55009415 it works.

**Comment by PackeTsar** [comment]
How does it break? What does it do?

**Comment by camwin** [comment]
PS C:\Users\me\Downloads\ASA-Cleanup-master\ASA-Cleanup-master> .\Binaries\ASA-Cleanup.exe -lie .\show_access-lists_inside.txt
Traceback (most recent call last):
  File "ASA-Cleanup.py", line 633, in <module>
    hdata = acl_hit_analysis(lines)
  File "ASA-Cleanup.py", line 125, in acl_hit_analysis
    table = make_table(["Name", "Total Hits"], sort_by_hits(totals))
  File "ASA-Cleanup.py", line 407, in make_table
    datalengthdict[item] = len(row[item]) # Then change the value of entry
TypeError: object of type 'long' has no len()
[14364] Failed to execute script ASA-Cleanup
PS C:\Users\me\Downloads\ASA-Cleanup-master\ASA-Cleanup-master> python.exe -V
Python 3.11.9
PS C:\Users\me\Downloads\ASA-Cleanup-master\ASA-Cleanup-master> python3.exe -V
Python 3.11.9
